graph LR;
    subgraph User
        U((User))
    end
    subgraph PC
        A0[Landing Page]
    end
    subgraph SSO
        B1[Login]
    end
    subgraph UP System
        C0[Company Creation/Association]
        C1[PC Subscription]
        C2[PC Trial]
        C3[Contract Signing]
        C4[Orders]
        C5[Payment]
        C6[Contracts]
    end
    subgraph Fadada / DocuSign
       D0[Template Module]
       D1[Signing Module]
       D2[Auth Module]
       D3[Contract Module]
    end
    subgraph Ops
     O((Ops))
    end
    subgraph Support System
        E0[Company Management]
        E1[User Management]
        E2[Template Management]
        E3[Signing Management]
        E4[Order Management]
        E5[Product and Discount Management]
    end
    subgraph Payment System
     F0[Payment]
    end
    subgraph Finance System
     style G0 fill:#ccc,stroke:#f66,stroke-width:2px,stroke-dasharray: 5 5;
     G0[Invoices and Billings]
    end
    C1 --> C0;
    C0 --> E0;
    E3 --> D1;
    E2 --> D0;
    A0 --> C1;
    A0 --> C2;
    A0 --> B1;
    B1 --> C1;
    B1 --> C2;
    C1 --> D2;
    C1 --> C3;
    C3 --> C4;
    C4 --> C5;
    C3 --> D1;
    C5 --> F0;
    C1 --> E0;
    U --> A0;
    O --> E0;
    C1--> E5;
    C4--> G0;
    C6--> D3;
