flowchart TD
    subgraph Support操作员操作
        Support操作员[Support操作员] -->|登录| Support平台[Support平台]
        Support平台 -->|管理和维护签约模版信息| 签约模版管理[签约模版信息管理维护]
        Support平台 -->|管理和维护签章信息| 签章管理[签章信息管理维护]
        Support平台 -->|查看签约列表| 签约列表查看[查看签约列表]
        签约列表查看 -->|进行签约操作| 签约操作[进行签约]
        Support平台 -->|查看计费管理信息| 计费管理查看[查看计费管理信息]
    end