flowchart TD
    subgraph 用户引导流程
        PC平台[PC landing page] -->|进入| PC详情页面[UP平台产品服务的PC详情页面]
        PC详情页面 -->|判断是否登录| 登录判断[是否已登录]
        登录判断 -->|已登录| 使用服务[使用UP平台产品服务]
        登录判断 -->|未登录| SSO平台[SSO平台]
        SSO平台 -->|登录| UP平台[UP平台产品服务]
        UP平台 -->|进入| 使用服务
    end

    