flowchart TD
    subgraph UP Subscription
        User((User)) -->|Subscribe to PC| X[auth check]
        X[Company Country Check] -->|Chinese| A
        X[Company Country Check] -->|Not Chinese| B
        A[Check Fadada Auth] -->|Authenticated| B1
        A[Check Fadada Auth] -->|Not Authenticated| A1
        A1[Fadada Auth] -->|Authenticated| B1
        B[DocuSign] --> B1
        B1[sign] --> C[payment]
        C --> E[Orders]
    end
    subgraph Support System
         AA[Operator with Sign permisson] --> |or auto-sign? |B1
    end