flowchart TD
    subgraph Free Trial or Subscription
        User[User] -->|Enter UP Platform| CheckIfBoundCompany[Check if Bound to Company]
        CheckIfBoundCompany -->|Not Bound| ApplyForTrial[Apply for Free Trial of PC Product]
        ApplyForTrial -->|Trial Operation| PCProduct[PC Product]
        CheckIfBoundCompany -->|Bound| SelectCompany[Select Bound Company]
        SelectCompany -->|Check Company Service Status| CheckIfCompanyActivated[Check if Company has Activated PC Product Service]
        CheckIfCompanyActivated -->|Activated| DirectEntry[Directly Enter PC Product]
        DirectEntry -->|Use Product| PCProduct
        CheckIfCompanyActivated -->|Not Activated| SubscribeProduct[Subscribe to PC Product]
        SubscribeProduct -->|Enter| OnlineContract[Online Contract]
        OnlineContract -->|Enter| OnlinePayment[Online Payment]
        OnlinePayment -->|Payment Successful| PCProduct
    end